//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telefon { get; set; }
        public int departmanId { get; set; }
        public Nullable<int> yoneticiId { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
    }
}
